### ISSUE TITLE
主应用 npm start 时报错

### ISSUE THREAD

**Issue by zhu-hongwei** [niexq/react-app-qiankun-main#14]
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/61079864/227415259-fd2d5878-6f39-44c8-a0c1-bd123429167f.png">

---

Compiled with problems:
×
ERROR
Cannot find module 'classnames'
    at webpackMissingModule (http://localhost:1122/static/js/bundle.js:20:50)
    at ./src/App.js (http://localhost:1122/static/js/bundle.js:20:135)
    at options.factory (http://localhost:1122/static/js/bundle.js:54228:31)
    at __webpack_require__ (http://localhost:1122/static/js/bundle.js:53674:33)
    at fn (http://localhost:1122/static/js/bundle.js:53885:21)
    at ./src/index.js (http://localhost:1122/static/js/bundle.js:353:62)
    at options.factory (http://localhost:1122/static/js/bundle.js:54228:31)
    at __webpack_require__ (http://localhost:1122/static/js/bundle.js:53674:33)
    at http://localhost:1122/static/js/bundle.js:54810:37
    at http://localhost:1122/static/js/bundle.js:54812:12
ERROR in ./src/App.js 9:0-36
Module not found: Error: Can't resolve 'classnames' in '/Users/mac/Desktop/init/src'

**Comment by zhu-hongwei** [comment]
```
npm install classnames --save
```

**Comment by zhu-hongwei** [comment]
new err


---


Compiled with problems:
×
ERROR
application 'react' died in status LOADING_SOURCE_CODE: Failed to fetch
TypeError: application 'react' died in status LOADING_SOURCE_CODE: Failed to fetch
    at importHTML (http://localhost:1122/static/js/bundle.js:7655:56)
    at importEntry (http://localhost:1122/static/js/bundle.js:7703:12)
    at _callee17$ (http://localhost:1122/static/js/bundle.js:15005:81)
    at tryCatch (http://localhost:1122/static/js/bundle.js:52586:17)
    at Generator.<anonymous> (http://localhost:1122/static/js/bundle.js:52667:22)
    at Generator.next (http://localhost:1122/static/js/bundle.js:52611:21)
    at asyncGeneratorStep (http://localhost:1122/static/js/bundle.js:53011:24)
    at _next (http://localhost:1122/static/js/bundle.js:53030:9)
    at http://localhost:1122/static/js/bundle.js:53035:7
    at new Promise (<anonymous>)

**Comment by zhu-hongwei** [comment]
https://qiankun.umijs.org/zh/faq

**Comment by niexq** [comment]
@zhu-hongwei 
看报错截图，应该是主应用依赖的classnames没安装上，建议删除node_modules，重新yarn试试。

**Comment by zhu-hongwei** [comment]
谢谢你的回复。
Good Luck.

**Comment by niexq** [comment]
> 谢谢你的回复。 Good Luck.

哈哈哈，感谢，共勉
